name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    # Clear npm cache to prevent EINTEGRITY errors
    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install dependencies
      run: npm install

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.2

    - name: Accept Android SDK licenses
      run: |
        echo "Accepting Android SDK licenses"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Create www directory
      run: |
        mkdir -p www
        # Copy web assets
        cp -r public/* www/

    - name: Remove existing Android platform
      run: |
        echo "Removing existing Android platform to ensure clean setup"
        rm -rf android

    - name: Add Android platform
      run: |
        echo "Adding Android platform"
        npx cap add android

    - name: Configure Gradle for JDK 17 compatibility
      run: |
        echo "Configuring Gradle for JDK 17 compatibility"
        echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
        echo "android.enableJetifier=true" >> gradle.properties
        echo "android.useAndroidX=true" >> gradle.properties
        echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties
        echo "org.gradle.daemon=false" >> gradle.properties

    - name: Update Gradle wrapper properties
      run: |
        echo "Updating Gradle wrapper properties"
        cd android
        echo "distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-all.zip" > gradle/wrapper/gradle-wrapper.properties

    - name: List project structure
      run: |
        echo "Project structure:"
        ls -la
        echo "Android directory contents:"
        ls -la android/
        echo "Android app directory contents:"
        ls -la android/app/
        echo "Gradle properties:"
        cat gradle.properties || echo "No gradle.properties file"
        echo "Gradle wrapper properties:"
        cat android/gradle/wrapper/gradle-wrapper.properties || echo "No gradle wrapper properties file"

    - name: Build Android project
      run: |
        echo "Copying and syncing Android project"
        npx cap copy android
        npx cap sync android

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Check Java version
      run: |
        echo "Checking Java version"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        echo "Gradle properties:"
        cat gradle.properties || echo "No gradle.properties file"

    - name: Build APK
      run: |
        echo "Building Release APK"
        cd android
        ./gradlew assembleRelease --stacktrace --info

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: android/app/build/outputs/apk/release/app-release-unsigned-signed.apk